---
version: 0.1.0
slug: cc2652p7-flasher
name: AiO Flasher
description: AiO Flasher
url: https://github.com/Xorfee/AddonZigbee/tree/main/zigstar-cc2652p7-flasher
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
image: "ghcr.io/mercenaruss/{arch}-addon-zigstar-cc2652p7-flasher"
init: false
options:
  network_device: null
  coordinator_fw: false
  router_fw: false
  firmware_url: ""
  trigger_bsl: false
schema:
  network_device: str?
  coordinator_fw: bool
  router_fw: bool
  firmware_url: str?
  trigger_bsl: bool?
stage: experimental
startup: once
boot: manual
