---
version: 0.1.0
slug: zigstar-cc2652-flasher
name: ZigStar TI CC2652 FW Flasher
description: ZigStar TI CC2652 firmware flasher add-on
url: >
  https://mercenaruss/zigstar_addons/tree/master/zigstar-cc2652-flasher/
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
gpio: false
hassio_api: true
image: "ghcr.io/mercenaruss/{arch}-addon-zigstar-cc2652-flasher"
init: false
options:
  network_device: null
  device: null
  trigger_bsl: false
  device_type: false
  flow_control: false
schema:
  device: device(subsystem=tty)?
  network_device: str?
  firmware_url: str?
  trigger_bsl: bool?
  device_type: bool?
  flow_control: bool?
stage: experimental
startup: once
boot: manual