---
version: 0.1.0
slug: zigstar-cc2652p-flasher
name: ZigStar TI CC2652P FW Flasher
description: ZigStar TI CC2652P firmware flasher add-on
## url: https://mercenaruss/zigstar_addons/tree/master/zigstar-cc2652-flasher/
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
gpio: false
hassio_api: true
## image: "ghcr.io/mercenaruss/{arch}-addon-zigstar-cc2652-flasher"
init: false
options:
  device: null
  network_device: null
  usb_mode: false
  koenk_fw: true
  firmware_url: ""
  trigger_bsl: true
schema:
  device: device(subsystem=tty)?
  network_device: str?
  usb_mode: bool?
  koenk_fw: bool
  firmware_url: str?
  trigger_bsl: bool?
stage: experimental
startup: once
boot: manual
