---
version: 0.4.0
slug: zigstar-cc2652p-flasher
name: ZigStar TI CC2652P/P7 FW Flasher
description: ZigStar TI CC2652P/P7 firmware flasher add-on
url: https://github.com/mercenaruss/zigstar_addons/tree/master/zigstar-cc2652-flasher/
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
image: "ghcr.io/mercenaruss/{arch}-addon-zigstar-cc2652-flasher"
init: false
options:
  device: null
  network_device: null
  usb_mode: false
  sonoff: false
  launchpad_fw: false
  cc1352p7_fw: false
  other_fw: false
  firmware_url: ""
  trigger_bsl: false
schema:
  device: device(subsystem=tty)?
  network_device: str?
  usb_mode: bool?
  sonoff: bool
  launchpad_fw: bool
  cc1352p7_fw: bool
  other_fw: bool
  firmware_url: str?
  trigger_bsl: bool?
stage: experimental
startup: once
boot: manual
